kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - single-cluster/manifests
  deleteNamespaces: true
  targets:
  - name: local
    clusterSelector:
      matchLabels:
        name: local
